# Generated by Django 3.1.7 on 2021-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210404_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Contribución', 'verbose_name_plural': 'Contribuciones'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='unlock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
