# Generated by Django 3.1.7 on 2021-04-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210406_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='is_Correct',
            new_name='is_correct',
        ),
    ]
