# Generated by Django 3.1.7 on 2021-04-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='level_name',
            field=models.CharField(default='Torcasa', max_length=255, verbose_name='Nombre de nivel'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_name',
            field=models.CharField(default='Torcasa', max_length=255, verbose_name='Nombre de nivel'),
        ),
    ]
