# Generated by Django 3.1.7 on 2021-04-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210423_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='unlock_date',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unlock_date', models.DateField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LogroUsuario',
                'verbose_name_plural': 'LogrosDeUsuario',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(through='users.UserAchievement', to='users.Achievement'),
        ),
    ]
