# Generated by Django 3.1.7 on 2021-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210425_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='level_name',
            field=models.CharField(default='Colibrí', max_length=255, verbose_name='Nombre de nivel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_name',
            field=models.CharField(default='Colibrí', max_length=255, verbose_name='Nombre de nivel'),
        ),
    ]
