# Generated by Django 3.1.7 on 2021-04-09 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_bird_sightings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='contribution',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('sightings', models.ManyToManyField(blank=True, null=True, to='posts.Sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribución',
                'verbose_name_plural': 'Contribuciones',
            },
        ),
    ]
