# Generated by Django 3.1.7 on 2021-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210419_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='sighted_birds',
            field=models.ManyToManyField(related_name='pepe', through='posts.Sighting', to='posts.Bird'),
        ),
    ]
