# Generated by Django 3.1.7 on 2021-05-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_expedition_sighted_birds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
