# Generated by Django 3.1.7 on 2021-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210601_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='is_verified',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
