# Generated by Django 3.1.7 on 2021-06-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210601_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
