# Generated by Django 3.1.7 on 2021-06-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210601_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='creation_date',
            new_name='date',
        ),
    ]
