# Generated by Django 3.1.7 on 2021-06-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210601_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='name',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='specie',
            new_name='scientific_name',
        ),
    ]
