# Generated by Django 3.1.7 on 2021-06-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210602_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AlterField(
            model_name='audio',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_audios', to='posts.sighting'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='photos/', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_photos', to='posts.sighting'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_videos', to='posts.sighting'),
        ),
        migrations.AlterField(
            model_name='video',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
