# Generated by Django 3.1.7 on 2021-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_sighting_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='sighting',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
