# Generated by Django 3.1.7 on 2021-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210607_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
