# Generated by Django 3.1.7 on 2021-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210607_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
