# Generated by Django 3.1.7 on 2021-06-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210607_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='is_correct',
            new_name='vote',
        ),
    ]
